// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function showNext(u) {
  console.log("You will be user " + String(u[/* id */0] + 1 | 0));
  return /* () */0;
}

showNext(/* record */[/* id */15]);

exports.showNext = showNext;
/*  Not a pure module */
